import type { Config } from "tailwindcss";
import animate from "tailwindcss-animate";

/** Theme aligned with repo root `index.html` (Tailwind CDN config). */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#3c0090",
        "outline-variant": "#3e4851",
        "on-primary-fixed": "#001e30",
        "primary-fixed-dim": "#8ccdff",
        "on-secondary": "#003641",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "inverse-on-surface": "#303030",
        "outline": "#88929c",
        "on-secondary-container": "#00596a",
        "on-surface": "#e2e2e2",
        "inverse-primary": "#006493",
        "tertiary-container": "#b291ff",
        "on-primary-container": "#003e5c",
        "secondary-container": "#00d5fd",
        error: "#ffb4ab",
        primary: "#16adf8",
        "tertiary-fixed": "#e9ddff",
        "on-background": "#e2e2e2",
        "surface-container-lowest": "#000d16",
        surface: "#001a2c",
        "secondary-fixed-dim": "#24d8ff",
        background: "#000810",
        "surface-container": "#00253d",
        "surface-bright": "#003554",
        "primary-container": "#16adf8",
        "on-surface-variant": "#bec8d2",
        "on-tertiary-container": "#4700a8",
        "on-primary": "#ffffff",
        "surface-container-high": "#002e4d",
        "on-primary-fixed-variant": "#004b70",
        "on-secondary-fixed-variant": "#004e5e",
        "surface-container-highest": "#003a61",
        "on-tertiary-fixed": "#23005b",
        "on-tertiary-fixed-variant": "#5700c9",
        "surface-container-low": "#001424",
        "tertiary-fixed-dim": "#d1bcff",
        "primary-fixed": "#cae6ff",
        "secondary-fixed": "#b1ecff",
        "surface-dim": "#000810",
        "surface-variant": "#003a61",
        "surface-tint": "#16adf8",
        secondary: "#05d7ff",
        tertiary: "#d1bcff",
        "on-error": "#690005",
        "on-secondary-fixed": "#001f27",
        "inverse-surface": "#e2e2e2",
        "deep-blue": "#001a2c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "8px",
        "container-max": "1280px",
        xxl: "80px",
        gutter: "24px",
        xl: "48px",
        md: "16px",
        unit: "4px",
        xs: "4px",
        lg: "24px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        h3: ["Space Grotesk", "sans-serif"],
        "label-caps": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        h1: ["Space Grotesk", "sans-serif"],
        h2: ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        h3: ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        h1: ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        h2: ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [animate],
} satisfies Config;
